# bibliotecas
import discord


class HelpEmbed:

    fun = discord.Embed(colour=discord.Colour.random())
    fun.set_author(name='Help with Fun commands', url='https://github.com/AkkoS2/YumeBot')
    fun.add_field(name='Fortune Teller', value='TBD', inline=False)
    fun.add_field(name='Like', value='TBD', inline=False)
    fun.add_field(name='Quiz', value='TBD', inline=False)
    fun.add_field(name='Random Question', value='TBD', inline=False)
    fun.add_field(name='Rickroll', value='TBD', inline=False)
    fun.add_field(name='Random ASCII', value='TBD', inline=False)
    fun.add_field(name='Chaos Emerald', value='TBD', inline=False)
    fun.add_field(name='Vay Hek', value='TBD', inline=False)
    fun.add_field(name='Emoji to ASCII', value='TBD', inline=False)
    fun.add_field(name='Text to ASCII', value='TBD', inline=False)
    fun.add_field(name='Soon™', value='TBD', inline=False)
    fun.add_field(name='Roll', value='TBD', inline=False)
    fun.add_field(name='Luck', value='TBD', inline=False)
    fun.add_field(name='Jokes', value='TBD', inline=False)
    fun.add_field(name='Coin', value='TBD', inline=False)
    fun.add_field(name='Uwuify', value='TBD', inline=False)
    fun.add_field(name='Fortune Cookie', value='TBD', inline=False)
    fun.add_field(name='Rock, Paper, Scissors', value='TBD', inline=False)
    fun.add_field(name='Rate Things', value='TBD', inline=False)
    fun.add_field(name='Time to Duel', value='TBD', inline=False)
    fun.set_footer(text='I hope this will be useful to you~')

    image = discord.Embed(colour=discord.Colour.random())
    image.set_author(name='Help with Image commands', url='https://github.com/AkkoS2/YumeBot')
    image.add_field(name='Tumblr', value='TBD', inline=False)
    image.add_field(name='Imgur', value='TBD', inline=False)
    image.add_field(name='Catboy', value='TBD', inline=False)
    image.add_field(name='Catgirl', value='TBD', inline=False)
    image.add_field(name='Cat', value='TBD', inline=False)
    image.add_field(name='Dog', value='TBD', inline=False)
    image.add_field(name='Reddit', value='TBD', inline=False)
    image.set_footer(text='I hope this will be useful to you~')

    moderation = discord.Embed(colour=discord.Colour.random())
    moderation.set_author(name='Help with Moderation commands', url='https://github.com/AkkoS2/YumeBot')
    moderation.add_field(name='Clear', value='TBD', inline=False)
    moderation.add_field(name='Message Log', value='TBD', inline=False)
    moderation.add_field(name='Staff Log', value='TBD', inline=False)
    moderation.add_field(name='Create Category', value='TBD', inline=False)
    moderation.add_field(name='Create Text Channel', value='TBD', inline=False)
    moderation.add_field(name='Create Voice Channel', value='TBD', inline=False)
    moderation.add_field(name='Delete Category', value='TBD', inline=False)
    moderation.add_field(name='Delete Text Channel', value='TBD', inline=False)
    moderation.add_field(name='Delete Voice Channel', value='TBD', inline=False)
    moderation.add_field(name='Nuke Channel', value='TBD', inline=False)
    moderation.add_field(name='Clone Channel', value='TBD', inline=False)
    moderation.set_footer(text='I hope this will be useful to you~')

    music = discord.Embed(colour=discord.Colour.random())
    music.set_author(name='Help with Music commands', url='https://github.com/AkkoS2/YumeBot')
    music.add_field(name='Join', value='TBD', inline=False)
    music.add_field(name='Leave', value='TBD', inline=False)
    music.add_field(name='Play', value='TBD', inline=False)
    music.add_field(name='Now Playing', value='TBD', inline=False)
    music.add_field(name='Pause', value='TBD', inline=False)
    music.add_field(name='Stop', value='TBD', inline=False)
    music.add_field(name='Skip', value='TBD', inline=False)
    music.add_field(name='Repeat', value='TBD', inline=False)
    music.add_field(name='Queue', value='TBD', inline=False)
    music.add_field(name='Shuffle Queue', value='TBD', inline=False)
    music.add_field(name='Queue Repeat', value='TBD', inline=False)
    music.add_field(name='Reset', value='TBD', inline=False)
    music.set_footer(text='I hope this will be useful to you~')

    nsfw = discord.Embed(colour=discord.Colour.random())
    nsfw.set_author(name='Help with NSFW commands', url='https://github.com/AkkoS2/YumeBot')
    nsfw.add_field(name='Yande.re', value='TBD', inline=False)
    nsfw.add_field(name='Rule34', value='TBD', inline=False)
    nsfw.add_field(name='Gelbooru', value='TBD', inline=False)
    nsfw.add_field(name='Safebooru', value='TBD', inline=False)
    nsfw.add_field(name='Danbooru', value='TBD', inline=False)
    nsfw.add_field(name='Konachan', value='TBD', inline=False)
    nsfw.add_field(name='Sankaku Complex', value='TBD', inline=False)
    nsfw.add_field(name='Lewd ASCII', value='TBD', inline=False)
    nsfw.add_field(name='E621', value='TBD', inline=False)
    nsfw.add_field(name='Reddit', value='TBD', inline=False)
    nsfw.set_footer(text='I hope this will be useful to you~')

    roleplay = discord.Embed(colour=discord.Colour.random())
    roleplay.set_author(name='Help with Roleplay commands', url='https://github.com/AkkoS2/YumeBot')
    roleplay.add_field(name='Hug', value='TBD', inline=False)
    roleplay.add_field(name='Slap', value='TBD', inline=False)
    roleplay.add_field(name='Kiss', value='TBD', inline=False)
    roleplay.add_field(name='Pat', value='TBD', inline=False)
    roleplay.add_field(name='Lick', value='TBD', inline=False)
    roleplay.add_field(name='Cuddle', value='TBD', inline=False)
    roleplay.add_field(name='Bite', value='TBD', inline=False)
    roleplay.add_field(name='Glare', value='TBD', inline=False)
    roleplay.add_field(name='Poke', value='TBD', inline=False)
    roleplay.add_field(name='Punch', value='TBD', inline=False)
    roleplay.add_field(name='Shoot', value='TBD', inline=False)
    roleplay.add_field(name='Stare', value='TBD', inline=False)
    roleplay.add_field(name='Stomp', value='TBD', inline=False)
    roleplay.add_field(name='Spank', value='TBD', inline=False)
    roleplay.add_field(name='Boop', value='TBD', inline=False)
    roleplay.set_footer(text='I hope this will be useful to you~')

    actions = discord.Embed(colour=discord.Colour.random())
    actions.set_author(name='Help with Actions commands', url='https://github.com/AkkoS2/YumeBot')
    actions.add_field(name='Arrest', value='TBD', inline=False)
    actions.add_field(name='Greet', value='TBD', inline=False)
    actions.add_field(name='Spook', value='TBD', inline=False)
    actions.add_field(name='Smug', value='TBD', inline=False)
    actions.add_field(name='Party', value='TBD', inline=False)
    actions.add_field(name='Ship', value='TBD', inline=False)
    actions.add_field(name='Kill', value='TBD', inline=False)
    actions.add_field(name='Clap', value='TBD', inline=False)
    actions.add_field(name='Dance', value='TBD', inline=False)
    actions.add_field(name='Shame', value='TBD', inline=False)
    actions.add_field(name='Facepalm', value='TBD', inline=False)
    actions.add_field(name='High Five', value='TBD', inline=False)
    actions.add_field(name='Laugh', value='TBD', inline=False)
    actions.add_field(name='Pout', value='TBD', inline=False)
    actions.add_field(name='Cheer', value='TBD', inline=False)
    actions.add_field(name='Purr', value='TBD', inline=False)
    actions.add_field(name='Sad', value='TBD', inline=False)
    actions.add_field(name='Shrug', value='TBD', inline=False)
    actions.add_field(name='Shy', value='TBD', inline=False)
    actions.add_field(name='Smile', value='TBD', inline=False)
    actions.add_field(name='Die', value='TBD', inline=False)
    actions.add_field(name='Wiggle', value='TBD', inline=False)
    actions.add_field(name='Wag', value='TBD', inline=False)
    actions.add_field(name='Cry', value='TBD', inline=False)
    actions.add_field(name='Run', value='TBD', inline=False)
    actions.set_footer(text='I hope this will be useful to you~')

    search = discord.Embed(colour=discord.Colour.random())
    search.set_author(name='Help with Search commands', url='https://github.com/AkkoS2/YumeBot')
    search.add_field(name='Minecraft Server Status', value='TBD', inline=False)
    search.add_field(name='Real Currency Converter', value='TBD', inline=False)
    search.add_field(name='AniList API', value='TBD', inline=False)
    search.add_field(name='MyAnimeList', value='TBD', inline=False)
    search.add_field(name='Anime Episodes', value='TBD', inline=False)
    search.add_field(name='Song Lyrics', value='TBD', inline=False)
    search.add_field(name='Manga', value='TBD', inline=False)
    search.add_field(name='Stock Market', value='TBD', inline=False)
    search.add_field(name='Tl;Dr', value='TBD', inline=False)
    search.add_field(name='Urban Dictionary', value='TBD', inline=False)
    search.add_field(name='YouTube Playlist', value='TBD', inline=False)
    search.add_field(name='YouTube Channel', value='TBD', inline=False)
    search.add_field(name='Crypto Value', value='TBD', inline=False)
    search.add_field(name='Anime Character', value='TBD', inline=False)
    search.add_field(name='Spotify Song', value='TBD', inline=False)
    search.add_field(name='Spotify Artist', value='TBD', inline=False)
    search.add_field(name='Spotify Album', value='TBD', inline=False)
    search.set_footer(text='I hope this will be useful to you~')

    utility = discord.Embed(colour=discord.Colour.random())
    utility.set_author(name='Help with Utility commands', url='https://github.com/AkkoS2/YumeBot')
    utility.add_field(name='Ping', value='TBD', inline=False)
    utility.add_field(name='Verify Status', value='TBD', inline=False)
    utility.add_field(name='Avatar', value='TBD', inline=False)
    utility.add_field(name='Waifu2x', value='TBD', inline=False)
    utility.add_field(name='Hexadecimal Color Generator', value='TBD', inline=False)
    utility.add_field(name='Password Generator', value='TBD', inline=False)
    utility.add_field(name='Colorize', value='TBD', inline=False)
    utility.add_field(name='Auto Role', value='TBD', inline=False)
    utility.add_field(name='Reaction Role', value='TBD', inline=False)
    utility.add_field(name='User Info', value='TBD', inline=False)
    utility.add_field(name='Server Info', value='TBD', inline=False)
    utility.add_field(name='Listen Chat Restriction', value='TBD', inline=False)
    utility.add_field(name='Ignore Chat Restriction', value='TBD', inline=False)
    utility.add_field(name='Blacklist', value='TBD', inline=False)
    utility.add_field(name='Whitelist', value='TBD', inline=False)
    utility.set_footer(text='I hope this will be useful to you~')

    mathematics = discord.Embed(colour=discord.Colour.random())
    mathematics.set_author(name='Help with Math commands', url='https://github.com/AkkoS2/YumeBot')
    mathematics.add_field(name='Addition', value='TBD', inline=False)
    mathematics.add_field(name='Subtraction', value='TBD', inline=False)
    mathematics.add_field(name='Division', value='TBD', inline=False)
    mathematics.add_field(name='Multiplication', value='TBD', inline=False)
    mathematics.add_field(name='Factorial', value='TBD', inline=False)
    mathematics.add_field(name='First Degree Equation', value='TBD', inline=False)
    mathematics.add_field(name='Second Degree Equation', value='TBD', inline=False)
    mathematics.add_field(name='Third Degree Equation', value='TBD', inline=False)
    mathematics.add_field(name='Arithmetic Progression', value='TBD', inline=False)
    mathematics.add_field(name='Geometric Progression', value='TBD', inline=False)
    mathematics.add_field(name='Simple Combination', value='TBD', inline=False)
    mathematics.add_field(name='Area of Plane Shapes', value='TBD', inline=False)
    mathematics.add_field(name='Volume of Solids', value='TBD', inline=False)
    mathematics.add_field(name='Trigonometric Ratios', value='TBD', inline=False)
    mathematics.add_field(name='Inverse Square Root', value='TBD', inline=False)
    mathematics.add_field(name='Square Root', value='TBD', inline=False)
    mathematics.set_footer(text='I hope this will be useful to you~')
